# Generated by Django 5.0.8 on 2024-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(
                default=1, upload_to="posts", verbose_name="Banner"
            ),
            preserve_default=False,
        ),
    ]
