# Generated by Django 5.0.8 on 2024-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(db_index=True, null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_ru",
            field=models.TextField(db_index=True, null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uz",
            field=models.TextField(db_index=True, null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="themes/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_en",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_ru",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="name_uz",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
