# Generated by Django 5.0.8 on 2024-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0003_notification_message_en_notification_message_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="banner",
            field=models.FileField(
                blank=True, null=True, upload_to="notifications", verbose_name="Banner"
            ),
        ),
    ]
