# Generated by Django 5.0.8 on 2024-12-18 10:39

import apps.mystories.models.posts
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0003_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.JSONField(verbose_name="Content"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                apps.mystories.models.posts.CastToText("content"),
                name="content_md5_idx",
            ),
        ),
    ]
