# Generated by Django 5.0.8 on 2024-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0003_tag_theme_alter_like_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(db_index=True, verbose_name="Izoh"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(db_index=True, verbose_name="Maqola"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
    ]
