# Generated by Django 5.0.8 on 2024-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0004_alter_comment_content_alter_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1, max_length=255, verbose_name="Slug"),
            preserve_default=False,
        ),
    ]
