# Generated by Django 5.0.8 on 2024-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0005_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
