# Generated by Django 5.0.8 on 2024-11-14 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0006_alter_post_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AddField(
            model_name="post",
            name="saved_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Saqlashlar"),
        ),
        migrations.CreateModel(
            name="Saved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="mystories.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saqlash",
                "verbose_name_plural": "Saqlashlar",
                "ordering": ["-created_at"],
                "unique_together": {("post", "user")},
            },
        ),
    ]
