# Generated by Django 5.0.8 on 2024-11-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0008_alter_comment_options_alter_like_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="theme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="mystories.theme",
                verbose_name="Theme",
            ),
            preserve_default=False,
        ),
    ]
