# Generated by Django 5.0.8 on 2024-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mystories", "0009_tag_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.JSONField(db_index=True, verbose_name="Content"),
        ),
    ]
