# Generated by Django 5.0.8 on 2024-11-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan sana"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Davlat nomi")),
                ("code", models.CharField(max_length=4, verbose_name="Davlat kodi")),
            ],
            options={
                "verbose_name": "Davlat",
                "verbose_name_plural": "Davlatlar",
            },
        ),
    ]
