# Generated by Django 5.0.8 on 2024-11-01 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="country",
            table="countries",
        ),
    ]
