# Generated by Django 5.0.8 on 2024-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0002_alter_country_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                db_index=True, max_length=4, verbose_name="Davlat kodi"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Davlat nomi"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
    ]
