# Generated by Django 5.0.8 on 2024-11-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0003_alter_country_code_alter_country_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countrys"},
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                db_index=True, max_length=4, verbose_name="Country code"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Updated at"
            ),
        ),
    ]
