# Generated by Django 5.0.8 on 2024-11-14 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0004_alter_country_options_alter_country_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countrys",
            },
        ),
    ]
