# Generated by Django 5.0.8 on 2024-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userdata",
            name="user_data_provide_d58aba_idx",
        ),
        migrations.RemoveIndex(
            model_name="userdata",
            name="user_data_uid_f3fdfc_idx",
        ),
        migrations.AlterField(
            model_name="userdata",
            name="extra_data",
            field=models.JSONField(
                blank=True, db_index=True, null=True, verbose_name="Extra data"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="provider",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("GOOGLE", "Google"),
                    ("GITHUB", "Github"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Provider",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="uid",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Provider ID"
            ),
        ),
    ]
