# Generated by Django 5.0.8 on 2024-11-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="register_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email orqali"),
                    ("GOOGLE", "Google orqali"),
                    ("GITHUB", "Github orqali"),
                ],
                default="EMAIL",
                max_length=20,
                verbose_name="Ro'yxatdan o'tish turi",
            ),
        ),
    ]
