# Generated by Django 5.0.8 on 2024-11-29 12:05

import core.config.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.config.s3.MediaStorage(),
                upload_to="avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
