# Generated by Django 5.0.8 on 2024-11-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_register_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Kuzatilayotganlar soni"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Kuzatuvchilar soni"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="Maxfiylik"),
        ),
        migrations.CreateModel(
            name="ActiveSessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan sana"
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("user_agent", models.TextField(verbose_name="Foydalanuvchi agenti")),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Joylashuv"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="So'ngi faoliyat"),
                ),
                (
                    "fcm_token",
                    models.CharField(max_length=255, verbose_name="FCM token"),
                ),
                (
                    "refresh_token",
                    models.CharField(max_length=255, verbose_name="Refresh token"),
                ),
                (
                    "access_token",
                    models.CharField(max_length=255, verbose_name="Access token"),
                ),
                ("data", models.JSONField(verbose_name="Ma'lumotlar")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Faol sessiya",
                "verbose_name_plural": "Faol sessiyalar",
                "db_table": "active_sessions",
            },
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan sana"
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kuzatuvchi",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kuzatilayotgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kuzatuvchi",
                "verbose_name_plural": "Kuzatuvchilar",
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan sana"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email orqali"),
                            ("GOOGLE", "Google orqali"),
                            ("GITHUB", "Github orqali"),
                        ],
                        max_length=20,
                        verbose_name="Provayder",
                    ),
                ),
                ("uid", models.CharField(max_length=100, verbose_name="Provayder ID")),
                ("extra_data", models.JSONField(verbose_name="Qo'shimcha ma'lumotlar")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi ma'lumoti",
                "verbose_name_plural": "Foydalanuvchi ma'lumotlari",
                "db_table": "user_data",
                "indexes": [
                    models.Index(
                        fields=["provider"], name="user_data_provide_d58aba_idx"
                    ),
                    models.Index(fields=["uid"], name="user_data_uid_f3fdfc_idx"),
                ],
            },
        ),
    ]
