# Generated by Django 5.0.8 on 2024-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_email_4b85f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_usernam_baeb4b_idx",
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="access_token",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Access token"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="data",
            field=models.JSONField(
                blank=True, db_index=True, null=True, verbose_name="Ma'lumotlar"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="FCM token",
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="ip",
            field=models.GenericIPAddressField(db_index=True, verbose_name="IP manzil"),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="last_activity",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="So'ngi faoliyat"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="location",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Joylashuv"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="refresh_token",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Refresh token"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="user_agent",
            field=models.TextField(db_index=True, verbose_name="Foydalanuvchi agenti"),
        ),
        migrations.AlterField(
            model_name="follower",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="Foydalanuvchi nomi",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Yaratilgan sana"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="O'zgartirilgan sana"
            ),
        ),
    ]
