# Generated by Django 5.0.8 on 2024-11-14 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0004_alter_country_options_alter_country_code_and_more"),
        ("users", "0005_remove_user_users_email_4b85f2_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activesessions",
            options={
                "verbose_name": "Active session",
                "verbose_name_plural": "Active sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="follower",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Follower",
                "verbose_name_plural": "Followers",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="userdata",
            options={"verbose_name": "User data", "verbose_name_plural": "User data"},
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="data",
            field=models.JSONField(
                blank=True, db_index=True, null=True, verbose_name="DATA"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="ip",
            field=models.GenericIPAddressField(
                db_index=True, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="last_activity",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Last activity"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="location",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="user_agent",
            field=models.TextField(db_index=True, verbose_name="User agent"),
        ),
        migrations.AlterField(
            model_name="follower",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Follower",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Following",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follower_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Follower count"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Following count"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="Private"),
        ),
        migrations.AlterField(
            model_name="user",
            name="register_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("GOOGLE", "Google"),
                    ("GITHUB", "Github"),
                ],
                default="EMAIL",
                max_length=20,
                verbose_name="Register type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                    ("MODERATOR", "Moderator"),
                ],
                default="USER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="extra_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Extra data"),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="provider",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("GOOGLE", "Google"),
                    ("GITHUB", "Github"),
                ],
                max_length=20,
                verbose_name="Provider",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="uid",
            field=models.CharField(max_length=100, verbose_name="Provider ID"),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Updated at"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
