# Generated by Django 5.0.8 on 2024-11-14 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_activesessions_options_alter_follower_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="follower",
            table="followers",
        ),
    ]
