# Generated by Django 5.0.8 on 2024-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_follower_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesessions",
            name="location",
            field=models.JSONField(blank=True, null=True, verbose_name="Location"),
        ),
    ]
