# Generated by Django 5.0.8 on 2024-11-22 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_activesessions_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activesessions",
            name="data",
        ),
    ]
