# Generated by Django 5.0.8 on 2024-11-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_activesessions_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesessions",
            name="access_token",
            field=models.TextField(db_index=True, verbose_name="Access token"),
        ),
        migrations.AlterField(
            model_name="activesessions",
            name="refresh_token",
            field=models.TextField(db_index=True, verbose_name="Refresh token"),
        ),
    ]
