# Generated by Django 5.0.8 on 2024-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_activesessions_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activesessions",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="Data"),
        ),
    ]
