# Generated by Django 5.0.8 on 2024-11-27 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_activesessions_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activesessions",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Active session",
                "verbose_name_plural": "Active sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="userdata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User data",
                "verbose_name_plural": "User data",
            },
        ),
    ]
